s = [[' ']*3, [' ']*3, [' ']*3]
p1, p2 = "You", "Computer"

''' Clear the terminal screen. '''
def clrscr(): print('\033c')

def board():
    clrscr()
    print("\n\n")
    print("				1          |2          |3     ")
    print("				           |           |      ")
    print("				     "+s[0][0]+"     |     "+s[0][1]+"     |     "+s[0][2])
    print("				           |           |      ")
    print("				___________|___________|___________")
    print("				4          |5          |6     ")
    print("				           |           |      ")
    print("				     "+s[1][0]+"     |     "+s[1][1]+"     |     "+s[1][2])
    print("				           |           |      ")
    print("				___________|___________|___________")
    print("				7          |8          |9     ")
    print("				           |           |      ")
    print("				     "+s[2][0]+"     |     "+s[2][1]+"     |     "+s[2][2])
    print("				           |           |      ")
    print("				           |           |      ")
    print('\n\n')

''' Clear the board for new game. '''
def clrb():
    global s
    s = [[' ']*3, [' ']*3, [' ']*3]

''' Check if the match is draw or needs to continue. '''
def check():
    for r in s:
        if ' ' in r: return 'c'
    return 'd'

''' Check which player wins, if none has won call check() function to see if the match has drawn or is still running. '''
def win(): 
    winner = ''
    for i in range(3):
        if s[i][0]==s[i][1] and s[i][1]==s[i][2] and s[i][0] != ' ': winner = s[i][0]
        if s[0][i]==s[1][i] and s[1][i]==s[2][i] and s[0][i] != ' ': winner = s[0][i]

    ''' Main Diagonal '''
    if s[0][0] == s[1][1] and s[1][1] == s[2][2] and s[0][0] != ' ': winner = s[0][0]

    ''' Secondary Diagonal '''
    if s[0][2] == s[1][1] and s[1][1] == s[2][0] and s[0][2] != ' ': winner = s[0][2]
        
    # if not winner: winner = check() 
    return winner if winner else check()

''' Print the result - winner, if someone won, draw otherwise. '''
def res():
    if win()!='d':
        print("\n\n\n\t\t\t"+(p1 if win()=='O' else p2)+" Won!")
        if p2 != "Computer": print("\t\t\tCONGRATULATIONS!!")
    else:
        print("\n\n\n\t\t\tG A M E  D R A W !!\n\n\n")

''' Get input on user's turn. '''
def ptrn(p):
    board()
    o = 'O' if p==1 else 'X'
    if p1 != "You": print("\t" + (p1 if p == 1 else p2) + "'s turn")
    else: print("\tYour turn")
    x = int(input("\n\tEnter a block no. :- "))
    while(x<1 or x>9):
        x = int(input("\n\tInvalid input. Enter again:-\a "))
    while(x>0 and x<10):
        if(x==1 and s[0][0]==' '): 
            s[0][0]=o
            break
        elif(x==2 and s[0][1]==' '): 
            s[0][1]=o
            break
        elif(x==3 and s[0][2]==' '): 
            s[0][2]=o
            break
        elif(x==4 and s[1][0]==' '): 
            s[1][0]=o
            break
        elif(x==5 and s[1][1]==' '): 
            s[1][1]=o
            break
        elif(x==6 and s[1][2]==' '): 
            s[1][2]=o
            break
        elif(x==7 and s[2][0]==' '): 
            s[2][0]=o
            break
        elif(x==8 and s[2][1]==' '): 
            s[2][1]=o
            break
        elif(x==9 and s[2][2]==' '): 
            s[2][2]=o
            break
        else:
            x = int(input("\n\tInvalid input. Enter again:- \a"))
    return x

"""def cg1()
{
    int x
    s[1][1]='X'
    x=ptrn(1)
    if(x%2)
    {
        switch(x)
        {
            case 1:s[2][2]='X'
                     x=ptrn(1)
                     if (x==2 or x==8)
                   {
                          s[0][2]='X'
                          x=ptrn(1)
                        if(x==7)
                            s[1][2]='X'
                         else
                            s[2][0]='X'
                   }
                     elif (x==4 or x==6)
                   {
                        s[2][0]='X'
                            x=ptrn(1)
                        if(x==3)
                            s[2][1]='X'
                        else
                            s[0][2]='X'

                   }
                     elif(x==3)
                   {
                        s[0][1]='X'
                        x=ptrn(1)
                        if(x!=8)
                            s[2][1]='X'
                        else
                        {
                            s[1][0]='X'
                            x=ptrn(1)
                            if (x!=6)
                                s[1][2]='X'
                            else
                                s[2][0]='X'
                        }
                     }
                   elif(x==7)
                   {
                    s[1][0]='X'
                    x=ptrn(1)
                    if(x!=6)
                    {
                        s[1][2]='X'
                    }
                    else
                    {
                        s[0][2]='X'
                        x=ptrn(1)
                        if(x!=8)
                        {
                            s[2][1]='X'
                        }
                        else
                        {
                            s[0][2]='X'
                        }
                    }
                   }
                   else
                   x=ptrn(1)
                     break
            case 3:s[2][0]='X'
                   x=ptrn(1)
                   if (x==2 or x==8)
                   {
                    s[0][0]='X'
                    x=ptrn(1)
                    if(x==9)
                        s[1][0]='X'
                    else
                        s[2][2]='X'

                   }
                   elif (x==4 or x==6)
                   {
                    s[2][2]='X'
                    x=ptrn(1)
                    if(x==1)
                        s[2][1]='X'
                    else
                        s[0][0]='X'

                   }
                   elif(x==9)
                   {
                    s[1][2]='X'
                    x=ptrn(1)
                    if(x!=4)
                    {
                        s[1][0]='X'
                    }
                    else
                    {
                        s[0][1]='X'
                        x=ptrn(1)
                        if (x!=8)
                        {
                            s[2][1]='X'
                        }
                        else
                        {
                            s[0][0]='X'
                        }
                    }
                   }
                   elif(x==1)
                   {
                    s[0][0]='X'
                    x=ptrn(1)
                    if(x!=8)
                    {
                        s[2][1]='X'
                    }
                    else
                    {
                        s[2][2]='X'
                        x=ptrn(1)
                        if(x!=4)
                        {
                            s[1][0]='X'
                        }
                        else
                        {
                            s[2][2]='X'
                        }
                    }
                   }
                   else
                   x=ptrn(1)
                   break
            case 7:s[0][2]='X'
                   x=ptrn(1)
                   if (x==4 or x==6)
                   {
                    s[0][0]='X'
                    x=ptrn(1)
                    if(x==9)
                        s[0][1]='X'
                    else
                        s[2][2]='X'

                   }
                   elif (x==8 or x==2)
                   {
                    s[2][2]='X'
                    x=ptrn(1)
                    if(x==1)
                        s[1][2]='X'
                    else
                        s[0][0]='X'

                   }
                   elif(x==1)
                   {
                    s[1][0]='X'
                    x=ptrn(1)
                    if(x!=6)
                    {
                        s[1][2]='X'
                    }
                    else
                    {
                        s[2][1]='X'
                        x=ptrn(1)
                        if (x!=2)
                        {
                            s[0][1]='X'
                        }
                        else
                        {
                            s[2][2]='X'
                        }
                    }
                   }
                   elif(x==9)
                   {
                    s[2][1]='X'
                    x=ptrn(1)
                    if(x!=2)
                    {
                        s[0][1]='X'
                    }
                    else
                    {
                        s[0][0]='X'
                        x=ptrn(1)
                        if(x!=6)
                        {
                            s[1][2]='X'
                        }
                        else
                        {
                            s[0][0]='X'
                        }
                    }
                   }
                   else
                   x=ptrn(1)
                   break
            case 9:s[0][0]='X'
                   x=ptrn(1)
                   if (x==2 or x==8)
                   {
                    s[2][0]='X'
                    x=ptrn(1)
                    if(x==3)
                        s[1][0]='X'
                    else
                        s[0][2]='X'

                   }
                   elif (x==4 or x==6)
                   {
                    s[0][2]='X'
                    x=ptrn(1)
                    if(x==7)
                        s[0][1]='X'
                    else
                        s[2][0]='X'

                   }
                   elif(x==7)
                   {
                    s[2][1]='X'
                    x=ptrn(1)
                    if(x!=2)
                    {
                        s[0][1]='X'
                    }
                    else
                    {
                        s[1][2]='X'
                        x=ptrn(1)
                        if (x!=4)
                        {
                            s[1][0]='X'
                        }
                        else
                        {
                            s[0][2]='X'
                        }
                    }
                   }
                   elif(x==3)
                   {
                    s[0][2]='X'
                    x=ptrn(1)
                    if(x!=4)
                    {
                        s[1][0]='X'
                    }
                    else
                    {
                        s[2][0]='X'
                        x=ptrn(1)
                        if(x!=2)
                        {
                            s[0][1]='X'
                        }
                        else
                        {
                            s[2][0]='X'
                        }
                    }
                   }
                   else
                   x=ptrn(1)
                   break
            default: x=ptrn(1)
        }
    }
    else
    {
        if(x==4 or x==6)
        {
            s[2][0]='X'
            x=ptrn(1)
            if(x==3)
            {
                s[2][2]='X'
                x=ptrn(1)
                if(x==1)
                    s[2][1]='X'
                else
                    s[0][0]='X'

            }
            else
            {
                s[0][2]='X'
            }
        }
        else
        {
            s[0][0]='X'
            x=ptrn(1)
            if(x==9)
            {
                s[2][0]='X'
                x=ptrn(1)
                if(x==3)
                    s[1][0]='X'
                else
                    s[0][2]='X'

            }
            else
            {
                s[2][2]='X'
            }
        }board()
    }
    res()
    return
}

def cg2()
{
    int x
    x=ptrn(1)
    switch(x)
    {
        case 5:s[2][2]='X'
               x=ptrn(1)
               if(x==1)
               {
                 s[0][2]='X'
                 x=ptrn(1)
                 if (x!=6)
                 {
                     s[1][2]='X'
                     board()
                     break
                 }
                 else
                     s[1][0]='X'
                 x=ptrn(1) 
                 if(x==7 or x==8)
                     s[0][1]='X'
                 else
                     s[2][1]='X'
                 ptrn(1)
                 board()
                 break
            }
            if(x==2)
            {
                 s[2][1]='X'
                 x=ptrn(1)
                 if(x!=7)
                 {
                     s[2][0]='X'
                     board()
                     break
                 }
                 else
                     s[0][2]='X'
                 x=ptrn(1)
                 if(x!=6)
                 {
                     s[1][2]='X'
                     board()
                     break
                 }
                 else
                     s[1][0]='X'
                 ptrn(1)
                 board()
                 break
            }
            if(x==3)
            {
                     s[2][0]='X'
                     x=ptrn(1)
                     if(x!=8)
                     {
                         s[2][1]='X'
                        board()
                         break
                     }
                    else
                         s[0][1]='X'
                     x=ptrn(1)
                     if(x==1 or x==4)
                        s[1][2]='X'
                     else
                         s[1][0]='X'
                     ptrn(1)
                    board()
                    break
               }
               if(x==4)
               {
                 s[1][2]='X'
                 x=ptrn(1)
                 if(x!=3)
                 {
                     s[0][2]='X'
                     board()
                     break
                 }
                 else
                     s[2][0]='X'
                 x=ptrn(1)
                 if(x!=8)
                 {
                     s[2][1]='X'
                     board()
                     break
                 }
                 else
                     s[0][1]='X'
                 ptrn(1)
                 board()
                 break
               }
               if(x==6)
               {
                 s[1][0]='X'
                 x=ptrn(1)
                 if(x==1 or x==2)
                 {
                     s[2][1]='X'
                     x=ptrn(1)
                     if(x!=7)
                     {
                         s[2][0]='X'
                         board()
                         break
                     }
                     else
                         s[0][2]='X'
                     ptrn(1)
                     board()
                     break
                 }
                 elif (x==3)
                 {
                     s[2][0]='X'
                     x=ptrn(1)
                     if(x!=8)
                     {
                         s[2][1]='X'
                         board()
                         break
                     }
                     else
                         s[0][1]='X'
                     ptrn(1)
                     board()
                     break
                 }
                 elif(x==7)
                 {
                     s[0][2]='X'
                     x=ptrn(1)
                     if(x==1 or x==2)
                         s[2][1]='X'
                     else
                         s[0][1]='X'
                     ptrn(1)
                     board()
                     break
                 }
                 elif(x==8)
                 {
                     s[0][1]='X'
                     x=ptrn(1)
                     s[2][0]='X'
                     ptrn(1)
                     board()
                     break
                 }
                 }
                 if(x==7)
                 {
                 s[0][2]='X'
                 x=ptrn(1)
                 if(x!=6)
                 {
                     s[1][2]='X'
                board()
                     break
                 }
                 else
                     s[1][0]='X'
                 x=ptrn(1)
                 if(x==1 or x==2)
                     s[2][1]='X'
                 else
                     s[0][1]='X'
                 ptrn(1)
             board()
                 break
                 }
                 if(x==8)
                 {
                 s[0][1]='X'
                 x=ptrn(1)
                 if(x==1 or x==4)
                 {
                     s[1][2]='X'
                     x=ptrn(1)
                     if(x!=3)
                     {
                         s[0][2]='X'
                   board()
                         break
                     }
                     else
                         s[2][0]='X'
                     ptrn(1)
                board()
                     break
                 }
                 if(x==3)
                 {
                     s[2][0]='X'
                     x=ptrn(1)
                     if(x==1 or x==4)
                         s[1][2]='X'
                     else
                         s[1][0]='X'
                     ptrn(1)
                board()
                     break
                 }
                 if(x==7)
                 {
                     s[0][2]='X'
                     x=ptrn(1)
                     if(x!=6)
                     {
                         s[1][2]='X'
                   board()
                         break
                     }
                     else
                         s[1][0]='X'
                     ptrn(1)
                board()
                     break
                 }
                 if(x==6)
                 {
                     s[1][0]='X'
                     x=ptrn(1)
                     if(x==1 or x==3)
                         s[2][0]='X'
                     else
                         s[0][2]='X'
                     ptrn(1)
                     board()
                 }
                 }
                 break
        case 1:s[1][1]='X'
                 x=ptrn(1)
                 if(x==3)
                 {
                s[0][1]='X'
                x=ptrn(1)
                if(x!=8)
                {
                    s[2][1]='X'
               board()
                     break
                }
                else
                    s[1][0]='X'
                x=ptrn(1)
                if(x!=6)
                {
                    s[1][2]='X'
               board()
                     break
                }
                else
                    s[2][2]='X'
                ptrn(1)
            board()
                     break
                 }
                 if(x==4)
                 {
                s[2][0]='X'
                x=ptrn(1)
                if(x!=3)
                {
                    s[0][2]='X'
               board()
                     break
                }
                else
                    s[0][1]='X'
                x=ptrn(1)
                if(x!=8)
                {
                    s[2][1]='X'
               board()
                     break
                }
                else
                    s[2][2]='X'
                ptrn(1)
            board()
                     break
                 }
                 if(x==2)
                 {
                s[0][2]='X'
                x=ptrn(1)
                if(x!=7)
                {
                    s[2][0]='X'
               board()
                     break
                }
                else
                    s[1][0]='X'
                x=ptrn(1)
                if(x!=6)
                {
                    s[1][2]='X'
               board()
                     break
                }
                else
                    s[2][2]='X'
                ptrn(1)
            board()
                     break
                 }
                 if(x==6)
                 {
                s[0][2]='X'
                x=ptrn(1)
                if(x!=7)
                {
                    s[2][0]='X'
               board()
                     break
                }
                else
                    s[1][0]='X'
                x=ptrn(1)
                if(x!=9)
                {
                    s[2][2]='X'
               board()
                     break
                }
                else
                    s[2][1]='X'
                ptrn(1)
            board()
                     break
                 }
                 if(x==7)
                 {
                s[1][0]='X'
                x=ptrn(1)
                if(x!=6)
                {
                    s[1][2]='X'
               board()
                     break
                }
                else
                    s[0][1]='X'
                x=ptrn(1)
                if(x!=8)
                {
                    s[2][1]='X'
               board()
                     break

                }
                else
                    s[2][2]='X'
                ptrn(1)
            board()
                     break
                 }
                 if(x==8)
                 {
                s[2][0]='X'
                x=ptrn(1)
                if(x!=3)
                {
                    s[0][2]='X'
               board()
                     break
                }
                else
                    s[0][1]='X'
                x=ptrn(1)
                if(x!=4)
                {
                    s[1][0]='X'
               board()
                     break
                }
                else
                    s[1][2]='X'
                ptrn(1)
            board()
                     break
                 }
                 if(x==9)
                 {
                s[0][1]='X'
                x=ptrn(1)
                if(x!=8)
                {
                    s[2][1]='X'
               board()
                     break
                }
                else
                    s[2][0]='X'
                x=ptrn(1)
                if(x!=3)
                {
                    s[0][2]='X'
               board()
                     break
                }
                else
                    s[1][2]='X'
                ptrn(1)
                board()
                 }
                 break
        case 2:s[1][1]='X'
                 x=ptrn(1)
                 if(x==1)
                 {
                s[0][2]='X'
                x=ptrn(1)
                if(x!=7)
                {
                    s[2][0]='X'
               board()
                     break
                }
                else
                    s[1][0]='X'
                x=ptrn(1)
                if(x!=6)
                {
                    s[1][2]='X'
               board()
                     break
                }
                else
                    s[2][2]='X'
                ptrn(1)
            board()
                     break
                 }
                 if(x==3)
                 {
                s[0][0]='X'
                x=ptrn(1)
                if(x!=9)
                {
                    s[2][2]='X'
               board()
                     break
                }
                else
                    s[1][2]='X'
                x=ptrn(1)
                if(x!=4)
                {
                    s[1][0]='X'
               board()
                     break
                }
                else
                    s[2][0]='X'
                ptrn(1)
                board()
                break
                 }
                 if(x==4)
                 {
                s[0][0]='X'
                x=ptrn(1)
                if(x!=9)
                {
                    s[2][2]='X'
               board()
                     break
                }
                else
                    s[2][0]='X'
                x=ptrn(1)
                if(x!=3)
                {
                    s[0][2]='X'
               board()
                     break
                }
                else
                    s[1][2]='X'
                ptrn(1)
            board()
                     break
                 }
                 if(x==6)
                 {
                s[0][2]='X'
                x=ptrn(1)
                if(x!=7)
                {
                    s[2][0]='X'
               board()
                     break
                }
                else
                    s[2][2]='X'
                x=ptrn(1)
                if(x!=1)
                {
                    s[0][0]='X'
               board()
                     break
                }
                else
                    s[1][0]='X'
                ptrn(1)
            board()
                     break
                 }
                 if(x==7)
                 {
                s[0][0]='X'
                x=ptrn(1)
                if(x!=9)
                {
                    s[2][2]='X'
               board()
                     break
                }
                else
                    s[2][1]='X'
                x=ptrn(1)
                if(x!=6)
                {
                    s[1][2]='X'
               board()
                     break
                }
                else
                    s[0][2]='X'
                ptrn(1)
            board()
                     break
                 }
                 if(x==8)
                 {
                s[0][0]='X'
                x=ptrn(1)
                if(x!=9)
                {
                    s[2][2]='X'
               board()
                     break
                }
                else
                    s[2][0]='X'
                x=ptrn(1)
                if(x!=3)
                {
                    s[0][2]='X'
               board()
                     break
                }
                else
                    s[1][0]='X'
                ptrn(1)
            board()
                     break
                 }
                 if(x==9)
                 {
                s[0][2]='X'
                x=ptrn(1)
                if(x!=7)
                {
                    s[2][0]='X'
               board()
                     break
                }
                else
                    s[2][1]='X'
                x=ptrn(1)
                if(x!=4)
                {
                    s[1][0]='X'
               board()
                     break
                }
                else
                    s[0][0]='X'
                ptrn(1)
                board()
                 }
                 break
        case 3:s[1][1]='X'
               x=ptrn(1)
               if(x==9)
               {
                s[1][2]='X'
                x=ptrn(1)
                if(x!=4)
                {
                    s[1][0]='X'
               board()
                     break
                }
                else
                    s[0][1]='X'
                x=ptrn(1)
                if(x!=8)
                {
                    s[2][1]='X'
               board()
                     break
                }
                else
                    s[2][0]='X'
                ptrn(1)
            board()
                     break
                 }
                 if(x==2)
                 {
                s[0][0]='X'
                x=ptrn(1)
                if(x!=9)
                {
                    s[2][2]='X'
               board()
                     break
                }
                else
                    s[1][2]='X'
                x=ptrn(1)
                if(x!=4)
                {
                    s[1][0]='X'
               board()
                     break
                }
                else
                    s[2][0]='X'
                ptrn(1)
            board()
                     break
                 }
                 if(x==6)
                 {
                s[2][2]='X'
                x=ptrn(1)
                if(x!=1)
                {
                    s[0][0]='X'
               board()
                     break
                }
                else
                    s[0][1]='X'
                x=ptrn(1)
                if(x!=8)
                {
                    s[2][1]='X'
               board()
                     break
                }
                else
                    s[2][0]='X'
                ptrn(1)
            board()
                     break
                 }
                 if(x==8)
                 {
                s[2][2]='X'
                x=ptrn(1)
                if(x!=1)
                {
                    s[0][0]='X'
               board()
                     break
                }
                else
                    s[0][1]='X'
                x=ptrn(1)
                if(x!=7)
                {
                    s[2][0]='X'
               board()
                     break
                }
                else
                    s[1][0]='X'
                ptrn(1)
            board()
                     break
                 }
                 if(x==1)
                 {
                s[0][1]='X'
                x=ptrn(1)
                if(x!=8)
                {
                    s[2][1]='X'
               board()
                     break
                }
                else
                    s[1][2]='X'
                x=ptrn(1)
                if(x!=4)
                {
                    s[1][0]='X'
               board()
                     break
                }
                else
                    s[2][0]='X'
                ptrn(1)
            board()
                     break
                 }
                 if(x==4)
                 {
                s[0][0]='X'
                x=ptrn(1)
                if(x!=9)
                {
                    s[2][2]='X'
               board()
                     break
                }
                else
                    s[1][2]='X'
                x=ptrn(1)
                if(x!=2)
                {
                    s[0][1]='X'
               board()
                     break
                }
                else
                    s[2][1]='X'
                ptrn(1)
            board()
                     break
                 }
                 if(x==7)
                 {
                s[1][2]='X'
                x=ptrn(1)
                if(x!=4)
                {
                    s[1][0]='X'
               board()
                     break
                }
                else
                    s[0][0]='X'
                x=ptrn(1)
                if(x!=9)
                {
                    s[2][2]='X'
               board()
                     break
                }
                else
                    s[2][1]='X'
                ptrn(1)
                board()
                 }
                 break
        case 4:s[1][1]='X'
                 x=ptrn(1)
                 if(x==7)
                 {
                s[0][0]='X'
                x=ptrn(1)
                if(x!=9)
                {
                    s[2][2]='X'
               board()
                     break
                }
                else
                    s[2][1]='X'
                x=ptrn(1)
                if(x!=2)
                {
                    s[0][1]='X'
               board()
                     break
                }
                else
                    s[0][2]='X'
                ptrn(1)
            board()
                     break
                 }
                 if(x==1)
                 {
                s[2][0]='X'
                x=ptrn(1)
                if(x!=3)
                {
                    s[0][2]='X'
               board()
                     break
                }
                else
                    s[0][1]='X'
                x=ptrn(1)
                if(x!=8)
                {
                    s[2][1]='X'
               board()
                     break
                }
                else
                    s[2][2]='X'
                ptrn(1)
            board()
                     break
                 }
                 if(x==8)
                 {
                s[2][0]='X'
                x=ptrn(1)
                if(x!=3)
                {
                    s[0][2]='X'
               board()
                     break
                }
                else
                    s[2][2]='X'
                x=ptrn(1)
                if(x!=1)
                {
                    s[0][0]='X'
               board()
                     break
                }
                else
                    s[0][1]='X'
                ptrn(1)
            board()
                     break
                 }
                 if(x==2)
                 {
                s[0][0]='X'
                x=ptrn(1)
                if(x!=9)
                {
                    s[2][2]='X'
               board()
                     break
                }
                else
                    s[0][2]='X'
                x=ptrn(1)
                if(x!=7)
                {
                    s[2][0]='X'
               board()
                     break
                }
                else
                    s[2][1]='X'
                ptrn(1)
            board()
                     break
                 }
                 if(x==9)
                 {
                s[2][0]='X'
                x=ptrn(1)
                if(x!=3)
                {
                    s[0][2]='X'
               board()
                     break
                }
                else
                    s[1][2]='X'
                x=ptrn(1)
                if(x!=2)
                {
                    s[0][1]='X'
               board()
                     break
                }
                else
                    s[0][0]='X'
                ptrn(1)
            board()
                     break
                 }
                 if(x==6)
                 {
                s[2][0]='X'
                x=ptrn(1)
                if(x!=3)
                {
                    s[0][2]='X'
               board()
                     break
                }
                else
                    s[2][2]='X'
                x=ptrn(1)
                if(x!=1)
                {
                    s[0][0]='X'
               board()
                     break
                }
                else
                    s[2][1]='X'
                ptrn(1)
            board()
                     break
                 }
                 if(x==3)
                 {
                s[0][0]='X'
                x=ptrn(1)
                if(x!=9)
                {
                    s[2][2]='X'
               board()
                     break
                }
                else
                    s[1][2]='X'
                x=ptrn(1)
                if(x!=8)
                {
                    s[2][1]='X'
                    board()
                    break
                }
                else
                    s[2][0]='X'
                ptrn(1)
                board()
                 }
                 break
        case 7:s[1][1]='X'
                 x=ptrn(1)
                 if(x==1)
                 {
                s[1][0]='X'
                x=ptrn(1)
                if(x!=6)
                {
                    s[1][2]='X'
               board()
                    break
                }
                else
                    s[2][1]='X'
                x=ptrn(1)
                if(x!=2)
                {
                    s[0][1]='X'
               board()
                    break
                }
                else
                    s[0][2]='X'
                ptrn(1)
            board()
                    break
                 }
                 if(x==8)
                 {
                s[2][2]='X'
                x=ptrn(1)
                if(x!=1)
                {
                    s[0][0]='X'
               board()
                    break
                }
                else
                    s[1][0]='X'
                x=ptrn(1)
                if(x!=6)
                {
                    s[1][2]='X'
               board()
                    break
                }
                else
                    s[0][2]='X'
                ptrn(1)
            board()
                    break
                 }
                 if(x==4)
                 {
                s[0][0]='X'
                x=ptrn(1)
                if(x!=9)
                {
                    s[2][2]='X'
               board()
                    break
                }
                else
                    s[2][1]='X'
                x=ptrn(1)
                if(x!=2)
                {
                    s[0][1]='X'
               board()
                    break
                }
                else
                    s[0][2]='X'
                ptrn(1)
            board()
                    break
                 }
                 if(x==2)
                 {
                s[0][0]='X'
                x=ptrn(1)
                if(x!=9)
                {
                    s[2][2]='X'
               board()
                    break
                }
                else
                    s[2][1]='X'
                x=ptrn(1)
                if(x!=3)
                {
                    s[0][2]='X'
               board()
                    break
                }
                else
                    s[1][2]='X'
                ptrn(1)
            board()
                    break
                 }
                 if(x==9)
                 {
                s[2][1]='X'
                x=ptrn(1)
                if(x!=2)
                {
                    s[0][1]='X'
               board()
                    break
                }
                else
                    s[1][0]='X'
                x=ptrn(1)
                if(x!=6)
                {
                    s[1][2]='X'
               board()
                    break
                }
                else
                    s[0][2]='X'
                ptrn(1)
            board()
                    break
                 }
                 if(x==6)
                 {
                s[2][2]='X'
                x=ptrn(1)
                if(x!=1)
                {
                    s[0][0]='X'
               board()
                    break
                }
                else
                    s[1][0]='X'
                x=ptrn(1)
                if(x!=8)
                {
                    s[2][1]='X'
               board()
                    break
                }
                else
                    s[0][1]='X'
                ptrn(1)
            board()
                    break
                 }
                 if(x==3)
                 {
                s[1][0]='X'
                x=ptrn(1)
                if(x!=6)
                {
                    s[1][2]='X'
               board()
                    break
                }
                else
                    s[2][2]='X'
                x=ptrn(1)
                if(x!=1)
                {
                    s[0][0]='X'
               board()
                    break
                }
                else
                    s[0][1]='X'
                ptrn(1)
                board()
                 }
                 break
        case 6:s[1][1]='X'
                 x=ptrn(1)
                 if(x==3)
                 {
                s[2][2]='X'
                x=ptrn(1)
                if(x!=1)
                {
                    s[0][0]='X'
               board()
                    break
                }
                else
                    s[0][1]='X'
                x=ptrn(1)
                if(x!=8)
                {
                    s[2][1]='X'
               board()
                    break
                }
                else
                    s[2][0]='X'
                ptrn(1)
            board()
                    break
                 }
                 if(x==9)
                 {
                s[0][2]='X'
                x=ptrn(1)
                if(x!=7)
                {
                    s[2][0]='X'
               board()
                    break
                }
                else
                    s[2][1]='X'
                x=ptrn(1)
                if(x!=2)
                {
                    s[0][1]='X'
                    board()
                    break
                }
                else
                    s[0][0]='X'
                ptrn(1)
            board()
                    break
                 }
                 if(x==2)
                 {
                s[0][2]='X'
                x=ptrn(1)
                if(x!=7)
                {
                    s[2][0]='X'
               board()
                    break
                }
                else
                    s[0][0]='X'
                x=ptrn(1)
                if(x!=9)
                {
                    s[2][2]='X'
               board()
                    break
                }
                else
                    s[2][1]='X'
                ptrn(1)
            board()
                    break
                 }
                 if(x==8)
                 {
                s[2][2]='X'
                x=ptrn(1)
                if(x!=1)
                {
                    s[0][0]='X'
               board()
                    break
                }
                else
                    s[2][0]='X'
                x=ptrn(1)
                if(x!=3)
                {
                    s[0][2]='X'
               board()
                    break
                }
                else
                    s[0][1]='X'
                ptrn(1)
            board()
                    break
                 }
                 if(x==1)
                 {
                s[0][2]='X'
                x=ptrn(1)
                if(x!=7)
                {
                    s[2][0]='X'
               board()
                    break
                }
                else
                    s[1][0]='X'
                x=ptrn(1)
                if(x!=8)
                {
                    s[2][1]='X'
               board()
                    break
                }
                else
                    s[2][2]='X'
                ptrn(1)
            board()
                    break
                 }
                 if(x==4)
                 {
                s[0][2]='X'
                x=ptrn(1)
                if(x!=7)
                {
                    s[2][0]='X'
               board()
                    break
                }
                else
                    s[0][0]='X'
                x=ptrn(1)
                if(x!=9)
                {
                    s[2][2]='X'
               board()
                    break
                }
                else
                    s[0][1]='X'
                ptrn(1)
            board()
                    break
                 }
                 if(x==7)
                 {
                s[2][2]='X'
                x=ptrn(1)
                if(x!=1)
                {
                    s[0][0]='X'
               board()
                    break
                }
                else
                    s[1][0]='X'
                x=ptrn(1)
                if(x!=2)
                {
                    s[0][1]='X'
               board()
                    break
                }
                else
                    s[0][2]='X'
                ptrn(1)
                board()
                 }
                 break
        case 9:s[1][1]='X'
                 x=ptrn(1)
                 if(x==7)
                 {
                s[2][1]='X'
                x=ptrn(1)
                if(x!=2)
                {
                    s[0][1]='X'
               board()
                    break
                }
                else
                    s[1][2]='X'
                x=ptrn(1)
                if(x!=4)
                {
                    s[1][0]='X'
               board()
                    break
                }
                else
                    s[0][0]='X'
                ptrn(1)
            board()
                    break
                 }
                 if(x==6)
                 {
                s[0][2]='X'
                x=ptrn(1)
                if(x!=7)
                {
                    s[2][2]='X'
               board()
                    break
                }
                else
                    s[2][1]='X'
                x=ptrn(1)
                if(x!=2)
                {
                    s[0][1]='X'
               board()
                    break
                }
                else
                    s[0][0]='X'
                ptrn(1)
            board()
                    break
                 }
                 if(x==8)
                 {
                s[2][0]='X'
                x=ptrn(1)
                if(x!=3)
                {
                    s[0][2]='X'
               board()
                    break
                }
                else
                    s[1][2]='X'
                x=ptrn(1)
                if(x!=4)
                {
                    s[1][0]='X'
               board()
                    break
                }
                else
                    s[0][0]='X'
                ptrn(1)
            board()
                    break
                 }
                 if(x==4)
                 {
                s[2][0]='X'
                x=ptrn(1)
                if(x!=3)
                {
                    s[0][2]='X'
               board()
                    break
                }
                else
                    s[1][2]='X'
                x=ptrn(1)
                if(x!=1)
                {
                    s[0][0]='X'
               board()
                    break
                }
                else
                    s[0][1]='X'
                ptrn(1)
            board()
                    break
                 }
                 if(x==3)
                 {
                s[1][2]='X'
                x=ptrn(1)
                if(x!=4)
                {
                    s[1][0]='X'
               board()
                    break
                }
                else
                    s[2][1]='X'
                x=ptrn(1)
                if(x!=2)
                {
                    s[0][1]='X'
               board()
                    break
                }
                else
                    s[0][0]='X'
                ptrn(1)
            board()
                    break
                 }
                 if(x==2)
                 {
                s[0][2]='X'
                x=ptrn(1)
                if(x!=7)
                {
                    s[2][0]='X'
               board()
                    break
                }
                else
                    s[2][1]='X'
                x=ptrn(1)
                if(x!=6)
                {
                    s[1][2]='X'
               board()
                    break
                }
                else
                    s[1][0]='X'
                ptrn(1)
            board()
                    break
                 }
                 if(x==1)
                 {
                s[2][1]='X'
                x=ptrn(1)
                if(x!=2)
                {
                    s[0][1]='X'
               board()
                    break
                }
                else
                    s[0][2]='X'
                x=ptrn(1)
                if(x!=7)
                {
                    s[2][0]='X'
               board()
                    break
                }
                else
                    s[1][0]='X'
                ptrn(1)
                 }
                 break
        case 8:s[1][1]='X'
                 x=ptrn(1)
                 if(x==9)
                 {
                s[2][0]='X'
                x=ptrn(1)
                if(x!=3)
                {
                    s[0][2]='X'
               board()
                    break
                }
                else
                    s[1][2]='X'
                x=ptrn(1)
                if(x!=4)
                {
                    s[1][0]='X'
               board()
                    break
                }
                else
                    s[0][0]='X'
                ptrn(1)
            board()
                    break
                 }
                 if(x==7)
                 {
                s[2][2]='X'
                x=ptrn(1)
                if(x!=1)
                {
                    s[0][0]='X'
               board()
                    break
                }
                else
                    s[1][0]='X'
                x=ptrn(1)
                if(x!=6)
                {
                    s[1][2]='X'
               board()
                    break
                }
                else
                    s[0][2]='X'
                ptrn(1)
            board()
                    break
                 }
                 if(x==6)
                 {
                s[2][2]='X'
                x=ptrn(1)
                if(x!=1)
                {
                    s[0][0]='X'
               board()
                    break
                }
                else
                    s[0][2]='X'
                x=ptrn(1)
                if(x!=7)
                {
                    s[2][0]='X'
               board()
                    break
                }
                else
                    s[1][0]='X'
                ptrn(1)
            board()
                    break
                 }
                 if(x==4)
                 {
                s[2][0]='X'
                x=ptrn(1)
                if(x!=3)
                {
                    s[0][2]='X'
               board()
                    break
                }
                else
                    s[0][0]='X'
                x=ptrn(1)
                if(x!=9)
                {
                    s[2][2]='X'
               board()
                    break
                }
                else
                    s[1][2]='X'
                ptrn(1)
            board()
                    break
                 }
                 if(x==3)
                 {
                s[2][2]='X'
                x=ptrn(1)
                if(x!=1)
                {
                    s[0][0]='X'
               board()
                    break
                }
                else
                    s[0][1]='X'
                x=ptrn(1)
                if(x!=4)
                {
                    s[1][0]='X'
               board()
                    break
                }
                else
                    s[2][0]='X'
                ptrn(1)
            board()
                    break
                 }
                 if(x==2)
                 {
                s[2][2]='X'
                x=ptrn(1)
                if(x!=1)
                {
                    s[0][0]='X'
               board()
                    break
                }
                else
                    s[0][2]='X'
                x=ptrn(1)
                if(x!=7)
                {
                    s[2][0]='X'
               board()
                    break
                }
                else
                    s[1][2]='X'
                ptrn(1)
            board()
                    break
                 }
                 if(x==1)
                 {
                s[2][0]='X'
                x=ptrn(1)
                if(x!=3)
                {
                    s[0][2]='X'
               board()
                    break
                }
                else
                    s[0][1]='X'
                x=ptrn(1)
                if(x!=6)
                {
                    s[1][2]='X'
               board()
                    break
                }
                else
                    s[2][2]='X'
                ptrn(1)
            board()
                 }
                 break
    }
    res()
    return
}"""

def pg(): 
    while(win()=='c'):
        ptrn(2)
        if(win()=='c'):
            ptrn(1)
    board()
    res()

def menu():
    global p2, p1
    # print("\n\n\n\n\n\n\n\n\n\t\t\t1.Player Vs Player\n\n\n\t\t\t2.Computer Vs Player")
    # a = int(input("\n\n\n\n\n\n\n\n\n\t\t\tEnter your choice(1/2) :- "))

    # print('\033c')

    # if(a==2): 
    # {
    # 	print("\n\n\n\n\n\n\n\n\n\t\t\t1.Computer will start\n\n\n\t\t\t2.I will start")
    # 	print("\n\n\n\n\n\n\n\n\n\t\t\tEnter your choice(1/2) :- ")
    # 	cin>>a
    # 	board()
    # 	do
    # 	{
    # 		if(a==1)
    # 			cg1()
    # 		else
    # 			cg2()
    # 		print("\n\t\t\tDo yo want to play again? ")
    # 		cin>>y
    # 		if(y=='y' or y=='Y')
    # 			clrb()
    # 	}while(y=='y' or y=='Y')
    # }

    p1, p2 = 'player 2', 'player 1'

    # else:
    if 1:
        # p2 = input("\n\n\n\n\n\n\n\n\n			Player 1 Enter your name: ")
        # p1 = input("\n\n			Player 2 Enter your name: ")
        y = 'y'
        while(y=='y' or y=='Y'):
            pg()
            y = input("\n\t\t\tDo you want to play again? ")
            clrb()


menu()
