#include<iostream.h>
#include<conio.h>
#include<dos.h>
#include<string.h>
char s[3][3]={"   ","   ","   "};
char p1[15] = "You",p2[15] = "Computer";

void board()
{
	clrscr();
	cout<<"\n\n\n";
	cout<<"				1          |2          |3     "<<"\n";
	cout<<"				           |           |      "<<"\n";
	cout<<"				     "<<s[0][0]<<"     |     "<<s[0][1]<<"     |     "<<s[0][2]<<"\n";
	cout<<"				           |           |      "<<"\n";
	cout<<"				___________|___________|___________"<<"\n";
	cout<<"				4          |5          |6     "<<"\n";
	cout<<"				           |           |      "<<"\n";
	cout<<"				     "<<s[1][0]<<"     |     "<<s[1][1]<<"     |     "<<s[1][2]<<"\n";
	cout<<"				           |           |      "<<"\n";
	cout<<"				___________|___________|___________"<<"\n";
	cout<<"				7          |8          |9     "<<"\n";
	cout<<"				           |           |      "<<"\n";
	cout<<"				     "<<s[2][0]<<"     |     "<<s[2][1]<<"     |     "<<s[2][2]<<"\n";
	cout<<"				           |           |      "<<"\n";
	cout<<"				           |           |      "<<"\n";
}

void clrb()
{
	int i,j;
	for(i=0;i<3;i++)
		for(j=0;j<3;j++)
			s[i][j]=' ';
}

char check()
{
	int i,j;
	for(i=0;i<3;i++)
		for(j=0;j<3;j++)
			if(s[i][j]==' ')
				return 'c';
	return 'd';
}
char win()
{
	int i;
	for(i=0;i<3;i++)
	{
		if(s[i][0]==s[i][1]&&s[i][1]==s[i][2])
		{
			if(s[i][0]=='X')
				return 'x';
			else if(s[i][0]=='O')
				return 'o';
		}
		else if(s[0][i]==s[1][i]&&s[1][i]==s[2][i])
		{
				if(s[0][i]=='X')
				return 'x';
			else if(s[0][i]=='O')
				return 'o';
		}
	}
	if(s[0][0]==s[1][1]&&s[1][1]==s[2][2])
   {
			if(s[0][0]=='X')
				return 'x';
			else if(s[0][0]=='O')
				return 'o';
	}
	if(s[0][2]==s[1][1]&&s[1][1]==s[2][0])
   {
			if(s[0][2]=='X')
				return 'x';
			else if(s[0][2]=='O')
				return 'o';
	}
	return check();
}
void res()
{
	if(win()!='d')
	{
			cout<<"\n\n\n\t\t\t"<<((win()=='o')?p1:p2)<<" Won!";
			if (strcmp(p2, "Computer"))
				cout<<"  CONGRATULATIONS!!";
	}
		else
			cout<<"\n\n\n\t\t\tG A M E  D R A W !!\n\n\n";
}
int ptrn(int p)
{
	board();
	char o=(p==1)?'O':'X';
	int x;
	if(strcmp(p1, "You"))
		cout<<"\t"<<((p==1)?p1:p2)<<"'s turn";
	else
		cout<<"\tYour turn";
	cout<<"\n\tEnter a block no. :- ";
	cin>>x;
	while(x<1||x>9)
	{
		cout<<"\n\tInvalid input. Enter again:-\a ";
		cin>>x;
	}
	while(x>0&&x<10)
	{
		if(x==1 && s[0][0]==' ')
		{
			s[0][0]=o;
			break;
		}
		else if(x==2 && s[0][1]==' ')
		{
			s[0][1]=o;
			break;

		}
		else if(x==3 && s[0][2]==' ')
		{
			s[0][2]=o;
			break;
		}
		else if(x==4 && s[1][0]==' ')
		{
			s[1][0]=o;
			break;
		}
		else if(x==5 && s[1][1]==' ')
		{
			s[1][1]=o;
			break;
		}
		else if(x==6 && s[1][2]==' ')
		{
			s[1][2]=o;
			break;
		}
		else if(x==7 && s[2][0]==' ')
		{
			s[2][0]=o;
			break;
		}
		else if(x==8 && s[2][1]==' ')
		{
			s[2][1]=o;
			break;
		}
		else if(x==9 && s[2][2]==' ')
		{
			s[2][2]=o;
			break;
		}
		else
		{
			cout<<"\n\tInvalid input. Enter again:- \a";
			cin>>x;
		}
	}
	return x;
}
void cg1()
{
	int x;
	s[1][1]='X';
	x=ptrn(1);
	if(x%2)
	{
		switch(x)
		{
			case 1:s[2][2]='X';
					 x=ptrn(1);
					 if (x==2||x==8)
			       {
						  s[0][2]='X';
						  x=ptrn(1);
						if(x==7)
							s[1][2]='X';
						 else
							s[2][0]='X';
			       }
					 else if (x==4||x==6)
			       {
						s[2][0]='X';
							x=ptrn(1);
						if(x==3)
							s[2][1]='X';
						else
							s[0][2]='X';

			       }
					 else if(x==3)
			       {
						s[0][1]='X';
						x=ptrn(1);
						if(x!=8)
							s[2][1]='X';
						else
						{
							s[1][0]='X';
							x=ptrn(1);
							if (x!=6)
								s[1][2]='X';
							else
								s[2][0]='X';
						}
					 }
			       else if(x==7)
			       {
					s[1][0]='X';
					x=ptrn(1);
					if(x!=6)
					{
						s[1][2]='X';
					}
					else
					{
						s[0][2]='X';
						x=ptrn(1);
						if(x!=8)
						{
							s[2][1]='X';
						}
						else
						{
							s[0][2]='X';
						}
					}
			       }
			       else
			       x=ptrn(1);
					 break;
			case 3:s[2][0]='X';
			       x=ptrn(1);
			       if (x==2||x==8)
			       {
					s[0][0]='X';
					x=ptrn(1);
					if(x==9)
						s[1][0]='X';
					else
						s[2][2]='X';

			       }
			       else if (x==4||x==6)
			       {
					s[2][2]='X';
					x=ptrn(1);
					if(x==1)
						s[2][1]='X';
					else
						s[0][0]='X';

			       }
			       else if(x==9)
			       {
					s[1][2]='X';
					x=ptrn(1);
					if(x!=4)
					{
						s[1][0]='X';
					}
					else
					{
						s[0][1]='X';
						x=ptrn(1);
						if (x!=8)
						{
							s[2][1]='X';
						}
						else
						{
							s[0][0]='X';
						}
					}
			       }
			       else if(x==1)
			       {
					s[0][0]='X';
					x=ptrn(1);
					if(x!=8)
					{
						s[2][1]='X';
					}
					else
					{
						s[2][2]='X';
						x=ptrn(1);
						if(x!=4)
						{
							s[1][0]='X';
						}
						else
						{
							s[2][2]='X';
						}
					}
			       }
			       else
			       x=ptrn(1);
			       break;
			case 7:s[0][2]='X';
			       x=ptrn(1);
			       if (x==4||x==6)
			       {
					s[0][0]='X';
					x=ptrn(1);
					if(x==9)
						s[0][1]='X';
					else
						s[2][2]='X';

			       }
			       else if (x==8||x==2)
			       {
					s[2][2]='X';
					x=ptrn(1);
					if(x==1)
						s[1][2]='X';
					else
						s[0][0]='X';

			       }
			       else if(x==1)
			       {
					s[1][0]='X';
					x=ptrn(1);
					if(x!=6)
					{
						s[1][2]='X';
					}
					else
					{
						s[2][1]='X';
						x=ptrn(1);
						if (x!=2)
						{
							s[0][1]='X';
						}
						else
						{
							s[2][2]='X';
						}
					}
			       }
			       else if(x==9)
			       {
					s[2][1]='X';
					x=ptrn(1);
					if(x!=2)
					{
						s[0][1]='X';
					}
					else
					{
						s[0][0]='X';
						x=ptrn(1);
						if(x!=6)
						{
							s[1][2]='X';
						}
						else
						{
							s[0][0]='X';
						}
					}
			       }
			       else
			       x=ptrn(1);
			       break;
			case 9:s[0][0]='X';
			       x=ptrn(1);
			       if (x==2||x==8)
			       {
					s[2][0]='X';
					x=ptrn(1);
					if(x==3)
						s[1][0]='X';
					else
						s[0][2]='X';

			       }
			       else if (x==4||x==6)
			       {
					s[0][2]='X';
					x=ptrn(1);
					if(x==7)
						s[0][1]='X';
					else
						s[2][0]='X';

			       }
			       else if(x==7)
			       {
					s[2][1]='X';
					x=ptrn(1);
					if(x!=2)
					{
						s[0][1]='X';
					}
					else
					{
						s[1][2]='X';
						x=ptrn(1);
						if (x!=4)
						{
							s[1][0]='X';
						}
						else
						{
							s[0][2]='X';
						}
					}
			       }
			       else if(x==3)
			       {
					s[0][2]='X';
					x=ptrn(1);
					if(x!=4)
					{
						s[1][0]='X';
					}
					else
					{
						s[2][0]='X';
						x=ptrn(1);
						if(x!=2)
						{
							s[0][1]='X';
						}
						else
						{
							s[2][0]='X';
						}
					}
			       }
			       else
			       x=ptrn(1);
			       break;
			default: x=ptrn(1);
		}
	}
	else
	{
		if(x==4||x==6)
		{
			s[2][0]='X';
			x=ptrn(1);
			if(x==3)
			{
				s[2][2]='X';
				x=ptrn(1);
				if(x==1)
					s[2][1]='X';
				else
					s[0][0]='X';

			}
			else
			{
				s[0][2]='X';
			}
		}
		else
		{
			s[0][0]='X';
			x=ptrn(1);
			if(x==9)
			{
				s[2][0]='X';
				x=ptrn(1);
				if(x==3)
					s[1][0]='X';
				else
					s[0][2]='X';

			}
			else
			{
				s[2][2]='X';
			}
		}board();
	}
	res();
	return;
}
void cg2()
{
	int x;
	x=ptrn(1);
	switch(x)
	{
		case 5:s[2][2]='X';
		       x=ptrn(1);
		       if(x==1)
		       {
				 s[0][2]='X';
				 x=ptrn(1);
				 if (x!=6)
				 {
					 s[1][2]='X';
					 board();
					 break;
				 }
				 else
					 s[1][0]='X';
				 x=ptrn(1) ;
				 if(x==7||x==8)
					 s[0][1]='X';
				 else
					 s[2][1]='X';
				 ptrn(1);
				 board();
				 break;
			}
			if(x==2)
			{
				 s[2][1]='X';
				 x=ptrn(1);
				 if(x!=7)
				 {
					 s[2][0]='X';
					 board();
					 break;
				 }
				 else
					 s[0][2]='X';
				 x=ptrn(1);
				 if(x!=6)
				 {
					 s[1][2]='X';
					 board();
					 break;
				 }
				 else
					 s[1][0]='X';
				 ptrn(1);
				 board();
				 break;
			}
			if(x==3)
			{
				 	s[2][0]='X';
				 	x=ptrn(1);
				 	if(x!=8)
				 	{
					 	s[2][1]='X';
						board();
					 	break;
				 	}
					else
					 	s[0][1]='X';
				 	x=ptrn(1);
				 	if(x==1||x==4)
						s[1][2]='X';
				 	else
					 	s[1][0]='X';
				 	ptrn(1);
					board();
					break;
		       }
		       if(x==4)
		       {
				 s[1][2]='X';
				 x=ptrn(1);
				 if(x!=3)
				 {
					 s[0][2]='X';
					 board();
					 break;
				 }
				 else
					 s[2][0]='X';
				 x=ptrn(1);
				 if(x!=8)
				 {
					 s[2][1]='X';
					 board();
					 break;
				 }
				 else
					 s[0][1]='X';
				 ptrn(1);
				 board();
				 break;
		       }
		       if(x==6)
		       {
				 s[1][0]='X';
				 x=ptrn(1);
				 if(x==1||x==2)
				 {
					 s[2][1]='X';
					 x=ptrn(1);
					 if(x!=7)
					 {
						 s[2][0]='X';
						 board();
						 break;
					 }
					 else
						 s[0][2]='X';
					 ptrn(1);
					 board();
					 break;
				 }
				 else if (x==3)
				 {
					 s[2][0]='X';
					 x=ptrn(1);
					 if(x!=8)
					 {
						 s[2][1]='X';
						 board();
						 break;
					 }
					 else
						 s[0][1]='X';
					 ptrn(1);
					 board();
					 break;
				 }
				 else if(x==7)
				 {
					 s[0][2]='X';
					 x=ptrn(1);
					 if(x==1||x==2)
						 s[2][1]='X';
					 else
						 s[0][1]='X';
					 ptrn(1);
					 board();
					 break;
				 }
				 else if(x==8)
				 {
					 s[0][1]='X';
					 x=ptrn(1);
					 s[2][0]='X';
					 ptrn(1);
					 board();
					 break;
				 }
				 }
				 if(x==7)
				 {
				 s[0][2]='X';
				 x=ptrn(1);
				 if(x!=6)
				 {
					 s[1][2]='X';
                board();
					 break;
				 }
				 else
					 s[1][0]='X';
				 x=ptrn(1);
				 if(x==1||x==2)
					 s[2][1]='X';
				 else
					 s[0][1]='X';
				 ptrn(1);
             board();
				 break;
				 }
				 if(x==8)
				 {
				 s[0][1]='X';
				 x=ptrn(1);
				 if(x==1||x==4)
				 {
					 s[1][2]='X';
					 x=ptrn(1);
					 if(x!=3)
					 {
						 s[0][2]='X';
                   board();
						 break;
					 }
					 else
						 s[2][0]='X';
					 ptrn(1);
                board();
					 break;
				 }
				 if(x==3)
				 {
					 s[2][0]='X';
					 x=ptrn(1);
					 if(x==1||x==4)
						 s[1][2]='X';
					 else
						 s[1][0]='X';
					 ptrn(1);
                board();
					 break;
				 }
				 if(x==7)
				 {
					 s[0][2]='X';
					 x=ptrn(1);
					 if(x!=6)
					 {
						 s[1][2]='X';
                   board();
						 break;
					 }
					 else
						 s[1][0]='X';
					 ptrn(1);
                board();
					 break;
				 }
				 if(x==6)
				 {
					 s[1][0]='X';
					 x=ptrn(1);
					 if(x==1||x==3)
						 s[2][0]='X';
					 else
						 s[0][2]='X';
					 ptrn(1);
					 board();
				 }
				 }
				 break;
		case 1:s[1][1]='X';
				 x=ptrn(1);
				 if(x==3)
				 {
				s[0][1]='X';
				x=ptrn(1);
				if(x!=8)
				{
					s[2][1]='X';
               board();
					 break;
				}
				else
					s[1][0]='X';
				x=ptrn(1);
				if(x!=6)
				{
					s[1][2]='X';
               board();
					 break;
				}
				else
					s[2][2]='X';
				ptrn(1);
            board();
					 break;
				 }
				 if(x==4)
				 {
				s[2][0]='X';
				x=ptrn(1);
				if(x!=3)
				{
					s[0][2]='X';
               board();
					 break;
				}
				else
					s[0][1]='X';
				x=ptrn(1);
				if(x!=8)
				{
					s[2][1]='X';
               board();
					 break;
				}
				else
					s[2][2]='X';
				ptrn(1);
            board();
					 break;
				 }
				 if(x==2)
				 {
				s[0][2]='X';
				x=ptrn(1);
				if(x!=7)
				{
					s[2][0]='X';
               board();
					 break;
				}
				else
					s[1][0]='X';
				x=ptrn(1);
				if(x!=6)
				{
					s[1][2]='X';
               board();
					 break;
				}
				else
					s[2][2]='X';
				ptrn(1);
            board();
					 break;
				 }
				 if(x==6)
				 {
				s[0][2]='X';
				x=ptrn(1);
				if(x!=7)
				{
					s[2][0]='X';
               board();
					 break;
				}
				else
					s[1][0]='X';
				x=ptrn(1);
				if(x!=9)
				{
					s[2][2]='X';
               board();
					 break;
				}
				else
					s[2][1]='X';
				ptrn(1);
            board();
					 break;
				 }
				 if(x==7)
				 {
				s[1][0]='X';
				x=ptrn(1);
				if(x!=6)
				{
					s[1][2]='X';
               board();
					 break;
				}
				else
					s[0][1]='X';
				x=ptrn(1);
				if(x!=8)
				{
					s[2][1]='X';
               board();
					 break;

				}
				else
					s[2][2]='X';
				ptrn(1);
            board();
					 break;
				 }
				 if(x==8)
				 {
				s[2][0]='X';
				x=ptrn(1);
				if(x!=3)
				{
					s[0][2]='X';
               board();
					 break;
				}
				else
					s[0][1]='X';
				x=ptrn(1);
				if(x!=4)
				{
					s[1][0]='X';
               board();
					 break;
				}
				else
					s[1][2]='X';
				ptrn(1);
            board();
					 break;
				 }
				 if(x==9)
				 {
				s[0][1]='X';
				x=ptrn(1);
				if(x!=8)
				{
					s[2][1]='X';
               board();
					 break;
				}
				else
					s[2][0]='X';
				x=ptrn(1);
				if(x!=3)
				{
					s[0][2]='X';
               board();
					 break;
				}
				else
					s[1][2]='X';
				ptrn(1);
				board();
				 }
				 break;
		case 2:s[1][1]='X';
				 x=ptrn(1);
				 if(x==1)
				 {
				s[0][2]='X';
				x=ptrn(1);
				if(x!=7)
				{
					s[2][0]='X';
               board();
					 break;
				}
				else
					s[1][0]='X';
				x=ptrn(1);
				if(x!=6)
				{
					s[1][2]='X';
               board();
					 break;
				}
				else
					s[2][2]='X';
				ptrn(1);
            board();
					 break;
				 }
				 if(x==3)
				 {
				s[0][0]='X';
				x=ptrn(1);
				if(x!=9)
				{
					s[2][2]='X';
               board();
					 break;
				}
				else
					s[1][2]='X';
				x=ptrn(1);
				if(x!=4)
				{
					s[1][0]='X';
               board();
					 break;
				}
				else
					s[2][0]='X';
				ptrn(1);
				board();
				break;
				 }
				 if(x==4)
				 {
				s[0][0]='X';
				x=ptrn(1);
				if(x!=9)
				{
					s[2][2]='X';
               board();
					 break;
				}
				else
					s[2][0]='X';
				x=ptrn(1);
				if(x!=3)
				{
					s[0][2]='X';
               board();
					 break;
				}
				else
					s[1][2]='X';
				ptrn(1);
            board();
					 break;
				 }
				 if(x==6)
				 {
				s[0][2]='X';
				x=ptrn(1);
				if(x!=7)
				{
					s[2][0]='X';
               board();
					 break;
				}
				else
					s[2][2]='X';
				x=ptrn(1);
				if(x!=1)
				{
					s[0][0]='X';
               board();
					 break;
				}
				else
					s[1][0]='X';
				ptrn(1);
            board();
					 break;
				 }
				 if(x==7)
				 {
				s[0][0]='X';
				x=ptrn(1);
				if(x!=9)
				{
					s[2][2]='X';
               board();
					 break;
				}
				else
					s[2][1]='X';
				x=ptrn(1);
				if(x!=6)
				{
					s[1][2]='X';
               board();
					 break;
				}
				else
					s[0][2]='X';
				ptrn(1);
            board();
					 break;
				 }
				 if(x==8)
				 {
				s[0][0]='X';
				x=ptrn(1);
				if(x!=9)
				{
					s[2][2]='X';
               board();
					 break;
				}
				else
					s[2][0]='X';
				x=ptrn(1);
				if(x!=3)
				{
					s[0][2]='X';
               board();
					 break;
				}
				else
					s[1][0]='X';
				ptrn(1);
            board();
					 break;
				 }
				 if(x==9)
				 {
				s[0][2]='X';
				x=ptrn(1);
				if(x!=7)
				{
					s[2][0]='X';
               board();
					 break;
				}
				else
					s[2][1]='X';
				x=ptrn(1);
				if(x!=4)
				{
					s[1][0]='X';
               board();
					 break;
				}
				else
					s[0][0]='X';
				ptrn(1);
				board();
				 }
				 break;
		case 3:s[1][1]='X';
		       x=ptrn(1);
		       if(x==9)
		       {
				s[1][2]='X';
				x=ptrn(1);
				if(x!=4)
				{
					s[1][0]='X';
               board();
					 break;
				}
				else
					s[0][1]='X';
				x=ptrn(1);
				if(x!=8)
				{
					s[2][1]='X';
               board();
					 break;
				}
				else
					s[2][0]='X';
				ptrn(1);
            board();
					 break;
				 }
				 if(x==2)
				 {
				s[0][0]='X';
				x=ptrn(1);
				if(x!=9)
				{
					s[2][2]='X';
               board();
					 break;
				}
				else
					s[1][2]='X';
				x=ptrn(1);
				if(x!=4)
				{
					s[1][0]='X';
               board();
					 break;
				}
				else
					s[2][0]='X';
				ptrn(1);
            board();
					 break;
				 }
				 if(x==6)
				 {
				s[2][2]='X';
				x=ptrn(1);
				if(x!=1)
				{
					s[0][0]='X';
               board();
					 break;
				}
				else
					s[0][1]='X';
				x=ptrn(1);
				if(x!=8)
				{
					s[2][1]='X';
               board();
					 break;
				}
				else
					s[2][0]='X';
				ptrn(1);
            board();
					 break;
				 }
				 if(x==8)
				 {
				s[2][2]='X';
				x=ptrn(1);
				if(x!=1)
				{
					s[0][0]='X';
               board();
					 break;
				}
				else
					s[0][1]='X';
				x=ptrn(1);
				if(x!=7)
				{
					s[2][0]='X';
               board();
					 break;
				}
				else
					s[1][0]='X';
				ptrn(1);
            board();
					 break;
				 }
				 if(x==1)
				 {
				s[0][1]='X';
				x=ptrn(1);
				if(x!=8)
				{
					s[2][1]='X';
               board();
					 break;
				}
				else
					s[1][2]='X';
				x=ptrn(1);
				if(x!=4)
				{
					s[1][0]='X';
               board();
					 break;
				}
				else
					s[2][0]='X';
				ptrn(1);
            board();
					 break;
				 }
				 if(x==4)
				 {
				s[0][0]='X';
				x=ptrn(1);
				if(x!=9)
				{
					s[2][2]='X';
               board();
					 break;
				}
				else
					s[1][2]='X';
				x=ptrn(1);
				if(x!=2)
				{
					s[0][1]='X';
               board();
					 break;
				}
				else
					s[2][1]='X';
				ptrn(1);
            board();
					 break;
				 }
				 if(x==7)
				 {
				s[1][2]='X';
				x=ptrn(1);
				if(x!=4)
				{
					s[1][0]='X';
               board();
					 break;
				}
				else
					s[0][0]='X';
				x=ptrn(1);
				if(x!=9)
				{
					s[2][2]='X';
               board();
					 break;
				}
				else
					s[2][1]='X';
				ptrn(1);
				board();
				 }
				 break;
		case 4:s[1][1]='X';
				 x=ptrn(1);
				 if(x==7)
				 {
				s[0][0]='X';
				x=ptrn(1);
				if(x!=9)
				{
					s[2][2]='X';
               board();
					 break;
				}
				else
					s[2][1]='X';
				x=ptrn(1);
				if(x!=2)
				{
					s[0][1]='X';
               board();
					 break;
				}
				else
					s[0][2]='X';
				ptrn(1);
            board();
					 break;
				 }
				 if(x==1)
				 {
				s[2][0]='X';
				x=ptrn(1);
				if(x!=3)
				{
					s[0][2]='X';
               board();
					 break;
				}
				else
					s[0][1]='X';
				x=ptrn(1);
				if(x!=8)
				{
					s[2][1]='X';
               board();
					 break;
				}
				else
					s[2][2]='X';
				ptrn(1);
            board();
					 break;
				 }
				 if(x==8)
				 {
				s[2][0]='X';
				x=ptrn(1);
				if(x!=3)
				{
					s[0][2]='X';
               board();
					 break;
				}
				else
					s[2][2]='X';
				x=ptrn(1);
				if(x!=1)
				{
					s[0][0]='X';
               board();
					 break;
				}
				else
					s[0][1]='X';
				ptrn(1);
            board();
					 break;
				 }
				 if(x==2)
				 {
				s[0][0]='X';
				x=ptrn(1);
				if(x!=9)
				{
					s[2][2]='X';
               board();
					 break;
				}
				else
					s[0][2]='X';
				x=ptrn(1);
				if(x!=7)
				{
					s[2][0]='X';
               board();
					 break;
				}
				else
					s[2][1]='X';
				ptrn(1);
            board();
					 break;
				 }
				 if(x==9)
				 {
				s[2][0]='X';
				x=ptrn(1);
				if(x!=3)
				{
					s[0][2]='X';
               board();
					 break;
				}
				else
					s[1][2]='X';
				x=ptrn(1);
				if(x!=2)
				{
					s[0][1]='X';
               board();
					 break;
				}
				else
					s[0][0]='X';
				ptrn(1);
            board();
					 break;
				 }
				 if(x==6)
				 {
				s[2][0]='X';
				x=ptrn(1);
				if(x!=3)
				{
					s[0][2]='X';
               board();
					 break;
				}
				else
					s[2][2]='X';
				x=ptrn(1);
				if(x!=1)
				{
					s[0][0]='X';
               board();
					 break;
				}
				else
					s[2][1]='X';
				ptrn(1);
            board();
					 break;
				 }
				 if(x==3)
				 {
				s[0][0]='X';
				x=ptrn(1);
				if(x!=9)
				{
					s[2][2]='X';
               board();
					 break;
				}
				else
					s[1][2]='X';
				x=ptrn(1);
				if(x!=8)
				{
					s[2][1]='X';
					board();
					break;
				}
				else
					s[2][0]='X';
				ptrn(1);
				board();
				 }
				 break;
		case 7:s[1][1]='X';
				 x=ptrn(1);
				 if(x==1)
				 {
				s[1][0]='X';
				x=ptrn(1);
				if(x!=6)
				{
					s[1][2]='X';
               board();
					break;
				}
				else
					s[2][1]='X';
				x=ptrn(1);
				if(x!=2)
				{
					s[0][1]='X';
               board();
					break;
				}
				else
					s[0][2]='X';
				ptrn(1);
            board();
					break;
				 }
				 if(x==8)
				 {
				s[2][2]='X';
				x=ptrn(1);
				if(x!=1)
				{
					s[0][0]='X';
               board();
					break;
				}
				else
					s[1][0]='X';
				x=ptrn(1);
				if(x!=6)
				{
					s[1][2]='X';
               board();
					break;
				}
				else
					s[0][2]='X';
				ptrn(1);
            board();
					break;
				 }
				 if(x==4)
				 {
				s[0][0]='X';
				x=ptrn(1);
				if(x!=9)
				{
					s[2][2]='X';
               board();
					break;
				}
				else
					s[2][1]='X';
				x=ptrn(1);
				if(x!=2)
				{
					s[0][1]='X';
               board();
					break;
				}
				else
					s[0][2]='X';
				ptrn(1);
            board();
					break;
				 }
				 if(x==2)
				 {
				s[0][0]='X';
				x=ptrn(1);
				if(x!=9)
				{
					s[2][2]='X';
               board();
					break;
				}
				else
					s[2][1]='X';
				x=ptrn(1);
				if(x!=3)
				{
					s[0][2]='X';
               board();
					break;
				}
				else
					s[1][2]='X';
				ptrn(1);
            board();
					break;
				 }
				 if(x==9)
				 {
				s[2][1]='X';
				x=ptrn(1);
				if(x!=2)
				{
					s[0][1]='X';
               board();
					break;
				}
				else
					s[1][0]='X';
				x=ptrn(1);
				if(x!=6)
				{
					s[1][2]='X';
               board();
					break;
				}
				else
					s[0][2]='X';
				ptrn(1);
            board();
					break;
				 }
				 if(x==6)
				 {
				s[2][2]='X';
				x=ptrn(1);
				if(x!=1)
				{
					s[0][0]='X';
               board();
					break;
				}
				else
					s[1][0]='X';
				x=ptrn(1);
				if(x!=8)
				{
					s[2][1]='X';
               board();
					break;
				}
				else
					s[0][1]='X';
				ptrn(1);
            board();
					break;
				 }
				 if(x==3)
				 {
				s[1][0]='X';
				x=ptrn(1);
				if(x!=6)
				{
					s[1][2]='X';
               board();
					break;
				}
				else
					s[2][2]='X';
				x=ptrn(1);
				if(x!=1)
				{
					s[0][0]='X';
               board();
					break;
				}
				else
					s[0][1]='X';
				ptrn(1);
				board();
				 }
				 break;
		case 6:s[1][1]='X';
				 x=ptrn(1);
				 if(x==3)
				 {
				s[2][2]='X';
				x=ptrn(1);
				if(x!=1)
				{
					s[0][0]='X';
               board();
					break;
				}
				else
					s[0][1]='X';
				x=ptrn(1);
				if(x!=8)
				{
					s[2][1]='X';
               board();
					break;
				}
				else
					s[2][0]='X';
				ptrn(1);
            board();
					break;
				 }
				 if(x==9)
				 {
				s[0][2]='X';
				x=ptrn(1);
				if(x!=7)
				{
					s[2][0]='X';
               board();
					break;
				}
				else
					s[2][1]='X';
				x=ptrn(1);
				if(x!=2)
				{
					s[0][1]='X';
					board();
					break;
				}
				else
					s[0][0]='X';
				ptrn(1);
            board();
					break;
				 }
				 if(x==2)
				 {
				s[0][2]='X';
				x=ptrn(1);
				if(x!=7)
				{
					s[2][0]='X';
               board();
					break;
				}
				else
					s[0][0]='X';
				x=ptrn(1);
				if(x!=9)
				{
					s[2][2]='X';
               board();
					break;
				}
				else
					s[2][1]='X';
				ptrn(1);
            board();
					break;
				 }
				 if(x==8)
				 {
				s[2][2]='X';
				x=ptrn(1);
				if(x!=1)
				{
					s[0][0]='X';
               board();
					break;
				}
				else
					s[2][0]='X';
				x=ptrn(1);
				if(x!=3)
				{
					s[0][2]='X';
               board();
					break;
				}
				else
					s[0][1]='X';
				ptrn(1);
            board();
					break;
				 }
				 if(x==1)
				 {
				s[0][2]='X';
				x=ptrn(1);
				if(x!=7)
				{
					s[2][0]='X';
               board();
					break;
				}
				else
					s[1][0]='X';
				x=ptrn(1);
				if(x!=8)
				{
					s[2][1]='X';
               board();
					break;
				}
				else
					s[2][2]='X';
				ptrn(1);
            board();
					break;
				 }
				 if(x==4)
				 {
				s[0][2]='X';
				x=ptrn(1);
				if(x!=7)
				{
					s[2][0]='X';
               board();
					break;
				}
				else
					s[0][0]='X';
				x=ptrn(1);
				if(x!=9)
				{
					s[2][2]='X';
               board();
					break;
				}
				else
					s[0][1]='X';
				ptrn(1);
            board();
					break;
				 }
				 if(x==7)
				 {
				s[2][2]='X';
				x=ptrn(1);
				if(x!=1)
				{
					s[0][0]='X';
               board();
					break;
				}
				else
					s[1][0]='X';
				x=ptrn(1);
				if(x!=2)
				{
					s[0][1]='X';
               board();
					break;
				}
				else
					s[0][2]='X';
				ptrn(1);
				board();
				 }
				 break;
		case 9:s[1][1]='X';
				 x=ptrn(1);
				 if(x==7)
				 {
				s[2][1]='X';
				x=ptrn(1);
				if(x!=2)
				{
					s[0][1]='X';
               board();
					break;
				}
				else
					s[1][2]='X';
				x=ptrn(1);
				if(x!=4)
				{
					s[1][0]='X';
               board();
					break;
				}
				else
					s[0][0]='X';
				ptrn(1);
            board();
					break;
				 }
				 if(x==6)
				 {
				s[0][2]='X';
				x=ptrn(1);
				if(x!=7)
				{
					s[2][2]='X';
               board();
					break;
				}
				else
					s[2][1]='X';
				x=ptrn(1);
				if(x!=2)
				{
					s[0][1]='X';
               board();
					break;
				}
				else
					s[0][0]='X';
				ptrn(1);
            board();
					break;
				 }
				 if(x==8)
				 {
				s[2][0]='X';
				x=ptrn(1);
				if(x!=3)
				{
					s[0][2]='X';
               board();
					break;
				}
				else
					s[1][2]='X';
				x=ptrn(1);
				if(x!=4)
				{
					s[1][0]='X';
               board();
					break;
				}
				else
					s[0][0]='X';
				ptrn(1);
            board();
					break;
				 }
				 if(x==4)
				 {
				s[2][0]='X';
				x=ptrn(1);
				if(x!=3)
				{
					s[0][2]='X';
               board();
					break;
				}
				else
					s[1][2]='X';
				x=ptrn(1);
				if(x!=1)
				{
					s[0][0]='X';
               board();
					break;
				}
				else
					s[0][1]='X';
				ptrn(1);
            board();
					break;
				 }
				 if(x==3)
				 {
				s[1][2]='X';
				x=ptrn(1);
				if(x!=4)
				{
					s[1][0]='X';
               board();
					break;
				}
				else
					s[2][1]='X';
				x=ptrn(1);
				if(x!=2)
				{
					s[0][1]='X';
               board();
					break;
				}
				else
					s[0][0]='X';
				ptrn(1);
            board();
					break;
				 }
				 if(x==2)
				 {
				s[0][2]='X';
				x=ptrn(1);
				if(x!=7)
				{
					s[2][0]='X';
               board();
					break;
				}
				else
					s[2][1]='X';
				x=ptrn(1);
				if(x!=6)
				{
					s[1][2]='X';
               board();
					break;
				}
				else
					s[1][0]='X';
				ptrn(1);
            board();
					break;
				 }
				 if(x==1)
				 {
				s[2][1]='X';
				x=ptrn(1);
				if(x!=2)
				{
					s[0][1]='X';
               board();
					break;
				}
				else
					s[0][2]='X';
				x=ptrn(1);
				if(x!=7)
				{
					s[2][0]='X';
               board();
					break;
				}
				else
					s[1][0]='X';
				ptrn(1);
				 }
				 break;
		case 8:s[1][1]='X';
				 x=ptrn(1);
				 if(x==9)
				 {
				s[2][0]='X';
				x=ptrn(1);
				if(x!=3)
				{
					s[0][2]='X';
               board();
					break;
				}
				else
					s[1][2]='X';
				x=ptrn(1);
				if(x!=4)
				{
					s[1][0]='X';
               board();
					break;
				}
				else
					s[0][0]='X';
				ptrn(1);
            board();
					break;
				 }
				 if(x==7)
				 {
				s[2][2]='X';
				x=ptrn(1);
				if(x!=1)
				{
					s[0][0]='X';
               board();
					break;
				}
				else
					s[1][0]='X';
				x=ptrn(1);
				if(x!=6)
				{
					s[1][2]='X';
               board();
					break;
				}
				else
					s[0][2]='X';
				ptrn(1);
            board();
					break;
				 }
				 if(x==6)
				 {
				s[2][2]='X';
				x=ptrn(1);
				if(x!=1)
				{
					s[0][0]='X';
               board();
					break;
				}
				else
					s[0][2]='X';
				x=ptrn(1);
				if(x!=7)
				{
					s[2][0]='X';
               board();
					break;
				}
				else
					s[1][0]='X';
				ptrn(1);
            board();
					break;
				 }
				 if(x==4)
				 {
				s[2][0]='X';
				x=ptrn(1);
				if(x!=3)
				{
					s[0][2]='X';
               board();
					break;
				}
				else
					s[0][0]='X';
				x=ptrn(1);
				if(x!=9)
				{
					s[2][2]='X';
               board();
					break;
				}
				else
					s[1][2]='X';
				ptrn(1);
            board();
					break;
				 }
				 if(x==3)
				 {
				s[2][2]='X';
				x=ptrn(1);
				if(x!=1)
				{
					s[0][0]='X';
               board();
					break;
				}
				else
					s[0][1]='X';
				x=ptrn(1);
				if(x!=4)
				{
					s[1][0]='X';
               board();
					break;
				}
				else
					s[2][0]='X';
				ptrn(1);
            board();
					break;
				 }
				 if(x==2)
				 {
				s[2][2]='X';
				x=ptrn(1);
				if(x!=1)
				{
					s[0][0]='X';
               board();
					break;
				}
				else
					s[0][2]='X';
				x=ptrn(1);
				if(x!=7)
				{
					s[2][0]='X';
               board();
					break;
				}
				else
					s[1][2]='X';
				ptrn(1);
            board();
					break;
				 }
				 if(x==1)
				 {
				s[2][0]='X';
				x=ptrn(1);
				if(x!=3)
				{
					s[0][2]='X';
               board();
					break;
				}
				else
					s[0][1]='X';
				x=ptrn(1);
				if(x!=6)
				{
					s[1][2]='X';
               board();
					break;
				}
				else
					s[2][2]='X';
				ptrn(1);
            board();
				 }
				 break;
	}
	res();
	return;
}
void pg()
{
	board ();
	while(win()=='c')
	{
			ptrn(2);
		if(win()=='c')
			ptrn(1);
	}
board();
	res();
}

void menu()
{
	int a; char y;
	clrscr();
	cout<<"\n\n\n\n\n\n\n\n\n\t\t\t1.Player Vs Player\n\n\n\t\t\t2.Computer Vs Player";
	cout<<"\n\n\n\n\n\n\n\n\n\t\t\tEnter your choice(1/2) :- ";
	cin>>a;
	clrscr();
	if(a==2)
	{
		cout<<"\n\n\n\n\n\n\n\n\n\t\t\t1.Computer will start\n\n\n\t\t\t2.I will start";
		cout<<"\n\n\n\n\n\n\n\n\n\t\t\tEnter your choice(1/2) :- ";
		cin>>a;
		board();
		do
		{
			if(a==1)
				cg1();
			else
				cg2();
			cout<<"\n\t\t\tDo yo want to play again?";
			cin>>y;
			if(y=='y'||y=='Y')
				clrb();
		}while(y=='y'||y=='Y');
	}

	else

	{

		cout<<"\n\n\n\n\n\n\n\n\n			Player 1 Enter your name:-";

		cin>>p2;

		cout<<"\n\n			Player 2 Enter your name:-";

		cin>>p1;
		do
		{
			pg();
			cout<<"\n\t\t\tDo yo want to play again?";
			cin>>y;
			if(y=='y'||y=='Y')
				clrb();
		}while(y=='y'||y=='Y');
	}

}

void welcome()
{
	clrscr();
	cout<<"\n\n\n\n\n\n\n\n\n\t***        ***   ***********   ***                              \n";
	delay(200);
	cout<<"\t***        ***   ***********   ***                              \n";
	delay(200);
	cout<<"\t***        ***   ***           ***                              \n";
	delay(200);
	cout<<"\t***        ***   ***           ***                              \n";
	delay(200);
	cout<<"\t***        ***   ********      ***                              \n";
	delay(200);
	cout<<"\t***   **   ***   ********      ***                              \n";
	delay(200);
	cout<<"\t***  ****  ***   ***           ***            *    *    *    *  \n";
	delay(200);
	cout<<"\t*** **  ** ***   ***********   ***********   ***  ***  ***  *** \n";
	delay(200);
	cout<<"\t***        ***   ***********   ************   *    *    *    *  \n";
	delay(200);
	cout<<"                                             \n";
	delay(200);
	cout<<"                   ************     ********      ****       ****   ***********\n";
	delay(200);
	cout<<"                   ***********     **********     *** **   ** ***   **********\n";
	delay(200);
	cout<<"                   ***            ***       ***   ***  ****   ***   ***       \n";
	delay(200);
	cout<<"                   ***            ***       ***   ***   **    ***   ***       \n";
	delay(200);
	cout<<"                   ***            ***       ***   ***         ***   ********   \n";
	delay(200);
	cout<<"                   ***            ***       ***   ***         ***   *******   \n";
	delay(200);
	cout<<"                   ***            ***       ***   ***         ***   ***       \n";
	delay(200);
	cout<<"                   ***********     **********     ***         ***   ********** \n";
	delay(200);
	cout<<"                   ************     ********      ***         ***   ***********\n\n\n";
	delay(200);
	cout<<"              !!!                     !!!                     !!! \n";
	delay(200);
	cout<<"           !!!   !!!               !!!   !!!               !!!   !!!       \n";
	delay(200);
	cout<<"        !!!         !!!         !!!         !!!         !!!         !!!     \n";
	delay(200);
	cout<<"     !!!               !!!   !!!               !!!   !!!               !!!    \n";
	delay(200);
	cout<<"!!!!!                     !!!                     !!!                     !!!!!\n";
	delay(1000);
	cout<<"                                              \n";
	clrscr();
	cout<<"\n\n\n\n\n\n\n\n\n*************  *************  ************\n";
	delay(200);
	cout<<"*************  *************  *********** \n";
	delay(200);
	cout<<"     ***            ***       ***          \n";
	delay(200);
	cout<<"     ***            ***       ***          \n";
	delay(200);
	cout<<"     ***            ***       ***          \n";
	delay(200);
	cout<<"     ***            ***       ***          \n";
	delay(200);
	cout<<"     ***       *************  *********** \n";
	delay(200);
	cout<<"     ***       *************  ************\n";
	delay(200);
	cout<<" \n\n\n";
	delay(200);
	cout<<"                   *************       *****         ************\n";
	delay(200);
	cout<<"                   *************      *** ***        *********** \n";
	delay(200);
	cout<<"                        ***         ***     ***      ***         \n";
	delay(200);
	cout<<"                        ***        *************     ***         \n";
	delay(200);
	cout<<"                        ***       ***         ***    ***         \n";
	delay(200);
	cout<<"                        ***      ***           ***   *********** \n";
	delay(200);
	cout<<"                        ***     ***             ***  ************\n";
	delay(200);
	cout<<" \n\n\n";
	delay(200);
	cout<<"                                     *************    *********    ************\n";
	delay(200);
	cout<<"                                     *************  *************  *********** \n";
	delay(200);
	cout<<"                                          ***       ***       ***  ***         \n";
	delay(200);
	cout<<"                                          ***       ***       ***  *********   \n";
	delay(200);
	cout<<"                                          ***       ***       ***  ***         \n";
	delay(200);
	cout<<"                                          ***       *************  *********** \n";
	delay(200);
	cout<<"                                          ***         *********    ************\n";
	delay(4000);
}

void main()
{
	welcome();
	menu();
}
